import { phase2CapabilityDetailSlugs, phase2CategorySlugs, phase2ProjectSlugs, phase2Routes, type Phase2Locale } from "./phase2";

/**
 * Every string rendered by the phase 2 (v2) screens, in both locales.
 *
 * Conventions used by the display headings:
 *   "\n"      → hard line break
 *   "{word}"  → the word is rendered with the outline/gradient stroke treatment
 *
 * Hrefs live here too because slugs are not translatable by string
 * replacement — each locale points at its own canonical path.
 */

/** A term/value pair in a detail-screen definition list. `null` is filled in at render time. */
type Phase2Fact = { term: string; value: string | null };

export type Phase2RouteMap = {
    home: string;
    work: string;
    capabilities: string;
    about: string;
    insights: string;
    contact: string;
};

function buildCopy(locale: Phase2Locale) {
    const routes: Phase2RouteMap = phase2Routes[locale];
    const categories = phase2CategorySlugs[locale];
    const capabilityDetail = phase2CapabilityDetailSlugs[locale];

    return {
        categoryHref: {
            ai: `${routes.capabilities}/${categories.ai}`,
            photo: `${routes.capabilities}/${categories.photo}`,
            interactive: `${routes.capabilities}/${categories.interactive}`,
        },
        capabilityDetailHref: `${routes.capabilities}/${capabilityDetail.category}/${capabilityDetail.service}`,
        projectHref: (slug: string) => `${routes.work}/${slug}`,
        routes,
    };
}

const trPaths = buildCopy("tr");
const enPaths = buildCopy("en");

const en = {
    locale: "en" as Phase2Locale,
    routes: enPaths.routes,

    nav: {
        skipLink: "Skip to content",
        homeAria: "MetasoftCo home",
        primaryAria: "Primary navigation",
        mobileAria: "Mobile navigation",
        openMenu: "Open navigation",
        closeMenu: "Close navigation",
        localeSwitchAria: "Switch to Turkish",
        localeSwitchLabel: "TR / EN",
        cta: "Plan Your Activation",
        items: [
            { href: enPaths.routes.work, label: "Work" },
            { href: enPaths.routes.capabilities, label: "Capabilities" },
            { href: enPaths.routes.about, label: "About" },
            { href: enPaths.routes.insights, label: "Insights" },
            { href: enPaths.routes.contact, label: "Contact" },
        ],
    },

    footer: {
        tagline: "AI-powered experiential technology, built in Istanbul for brands and agencies.",
        exploreLabel: "EXPLORE",
        contactLabel: "CONTACT",
        followLabel: "FOLLOW",
        city: "Üniversite Mah. Sarıgül Sk. İstanbul Teknokent No: 37/1 İç Kapı No: 28, Avcılar / İstanbul",
        baseline: "Concept · Software · Physical production · Live operation",
        links: [
            { href: enPaths.routes.work, label: "Work" },
            { href: enPaths.routes.capabilities, label: "Capabilities" },
            { href: enPaths.routes.about, label: "About" },
            { href: enPaths.routes.contact, label: "Contact" },
        ],
    },

    home: {
        heroEyebrow: "AI-POWERED EXPERIENTIAL TECHNOLOGY",
        heroTitleOutline: "Experiences",
        heroTitleSolid: ["That", "Connect", "Brands"],
        heroTitleLabel: "Experiences that connect brands",
        heroFigureAlt: "Guests taking part in a Ray-Ban photo activation",
        heroFigureLabel: "LIVE PARTICIPATION",
        heroFigureCaption: "Ray-Ban · Strip Photo",
        heroBrief: "MetasoftCo creates branded photo, video, game and installation experiences for brands and agencies—combining creative direction, custom software and live production.",
        heroPrimaryCta: "Plan Your Activation",
        heroSecondaryCta: "View Selected Work",
        brandLoopAria: "Selected client collaborations",
        brandLoopEyebrow: "TRUSTED BY FORWARD-THINKING BRANDS",
        workEyebrow: "SELECTED WORK",
        workTitle: "Built\nfor\n{people}\nto take\npart.",
        workCopy: "Real people. Real moments. Experiences designed to invite participation and build lasting brand connection.",
        workLinkLabel: "View project",
        workFallbackCategory: "Live Experience",
        capabilitiesEyebrow: "CAPABILITIES",
        capabilitiesSrTitle: "Capabilities",
        capabilities: [
            { number: "01", title: "AI photo and video", copy: "Campaign-specific visual worlds that turn a guest portrait into branded content.", href: enPaths.categoryHref.ai },
            { number: "02", title: "Photo activations", copy: "Physical capture experiences designed around the venue, brand and sharing journey.", href: enPaths.categoryHref.photo },
            { number: "03", title: "Interactive games", copy: "Touch, movement and competition translated into playful branded participation.", href: enPaths.categoryHref.interactive },
            { number: "04", title: "Custom installations", copy: "Software, interfaces and physical systems developed as one live experience.", href: enPaths.routes.capabilities },
        ],
        processEyebrow: "HOW WE BUILD",
        processSrTitle: "How we build",
        process: [
            { number: "01", title: "Frame the brief", copy: "Audience, venue, campaign idea and desired guest journey." },
            { number: "02", title: "Prototype the experience", copy: "Creative direction, interaction flow and technical proof of concept." },
            { number: "03", title: "Build the system", copy: "Custom software, branded interface, content and physical integration." },
            { number: "04", title: "Deliver it live", copy: "Installation, event-day operation and a handover shaped around the brief." },
        ],
        valueEyebrow: "WHY INTERACTIVE",
        valueTitle: "Give the\naudience\na {role} in\nthe brand\nstory.",
        valueTitleLabel: "Give the audience a role in the brand story.",
        valuePoints: [
            "People remember what they do, not what they see.",
            "Participation creates emotional connection and trust.",
            "Shareable moments extend reach far beyond the venue.",
            "Data and insights help improve every activation.",
        ],
        finalEyebrow: "NEXT SIGNAL",
        finalTitle: "Make the next campaign\n{something people can enter.}",
        finalTitleLabel: "Make the next campaign something people can enter.",
        finalCopy: "Share the audience, venue and campaign goal. We’ll shape the interaction, system and live delivery around the brief.",
        finalCta: "Plan Your Activation",
    },

    about: {
        heroSolid: "We make",
        heroOutline: "technology physical.",
        heroLabel: "We make technology physical.",
        locationChip: "Istanbul  /  Since 2020",
        heroCopy: "We combine creative direction, custom software, physical production, and live operation to design and deliver experiences that connect brands and people in real time.",
        storyTitle: "Built in Istanbul.\nDelivered live.",
        storyParagraphs: [
            "We bring creative direction, software, physical production and live operation together under one roof.",
            "From concept to live delivery, we build experiences that are reliable, measurable and made to move people.",
        ],
        stats: [
            { value: "1,000+", label: "Live events" },
            { value: "100+", label: "Brands" },
            { value: "5+", label: "Years" },
            { value: "One", label: "End-to-end team" },
        ],
        principles: [
            { title: "Make it participatory", copy: "We design for action, not attention." },
            { title: "Build it for live conditions", copy: "We plan for the unexpected and deliver anyway." },
            { title: "Leave people with something", copy: "We create moments worth sharing." },
        ],
        finalSolid: "Bring us the brief.",
        finalOutline: "We’ll build the experience.",
        finalCta: "Plan Your Activation",
    },

    contact: {
        heroSolid: "Let’s build\nsomething",
        heroOutline: "people can enter.",
        heroLabel: "Let’s build something people can enter.",
        heroCopy: "Share the audience, venue and campaign goal. We’ll shape the experience.",
        asideTitle: "Start a conversation",
        location: "Istanbul, Türkiye",
        replyTime: "Reply within one business day",
        figureAlt: "MetasoftCo producers reviewing an event brief",
        form: {
            name: "Name *",
            namePlaceholder: "Your name",
            company: "Company *",
            companyPlaceholder: "Company name",
            email: "Email *",
            emailPlaceholder: "your@email.com",
            phone: "Phone *",
            phonePlaceholder: "+90 5XX XXX XX XX",
            event: "Event / campaign *",
            eventPlaceholder: "Event or campaign name",
            venue: "Venue + city *",
            venuePlaceholder: "Venue name and city",
            date: "Target date *",
            audience: "Expected audience *",
            audiencePlaceholder: "Estimated number of people",
            budget: "Budget range *",
            budgetPlaceholder: "Select budget range",
            budgetOptions: ["€5K–€10K", "€10K–€25K", "€25K+"],
            experienceLegend: "What type of experience are you planning? *",
            experienceTypes: ["AI Photo + Video", "Photo Activations", "Interactive Games", "Custom Installations"],
            brief: "Tell us about the brief *",
            briefPlaceholder: "Share your goals, audience, message, must-haves, and any references…",
            submit: "Send the brief",
            submitting: "Sending…",
            submitted: "Brief received",
            success: "Thanks — your brief is ready for our team. We’ll get back to you within one business day.",
            error: "The brief could not be sent. Please email info@metasoftco.com or try again.",
        },
        nextStepsTitle: "What happens next",
        nextSteps: [
            { number: "01", title: "We review", copy: "We review your brief and ask smart questions." },
            { number: "02", title: "We shape the approach", copy: "We design the right experience and technical plan." },
            { number: "03", title: "We plan delivery", copy: "We align the team, timeline and deliver with precision." },
        ],
        liteTitle: "Not ready for a full brief?",
        liteCopy: "That’s okay. Reach out or explore our work.",
        liteMailLabel: "Email us",
        liteWorkLabel: "Explore selected work",
        finalSolid: "The next",
        finalOutline: "live moment",
        finalTail: "starts here.",
    },

    work: {
        heroSolid: "Work that\npeople",
        heroOutline: "step into.",
        heroLabel: "Work that people step into.",
        heroCopy: "We design and deliver experiential activations that turn audiences into participants—and moments into brand connections.",
        catalogAria: "All work",
        cardLink: "View Project",
        ctaSolid: "Make the next\ncampaign",
        ctaOutline: "something people can enter.",
        ctaLabel: "Make the next campaign something people can enter.",
        ctaButton: "Plan Your Activation",
    },

    capabilities: {
        heroSolid: "We build\nthe system",
        heroOutline: "behind the moment.",
        heroLabel: "We build the system behind the moment.",
        heroCopy: "We combine creative direction, custom software, physical production and live operation to design and deliver experiences that connect brands and people in real time.",
        catalogAria: "Capabilities",
        cardLink: "Explore Capability",
        endToEndTitle: "One team,\nend to end",
        process: [
            { number: "01", title: "Brief", copy: "We listen, learn and align around goals, audience and success." },
            { number: "02", title: "Design", copy: "We craft the concept, experience flow and technical plan." },
            { number: "03", title: "Build", copy: "We build, test and integrate every element with precision." },
            { number: "04", title: "Deliver", copy: "We go live, run the show and optimize for impact." },
        ],
        ctaSolid: "Turn the brief",
        ctaOutline: "into a live experience.",
        ctaButton: "Plan Your Activation",
    },

    workDetail: {
        crumb: "Work  /  Case Study  /  01",
        heroSolid: "Ray-Ban ×",
        heroOutline: "Strip Photo",
        heroCopy: "An AI-powered photo activation that turns moments into iconic keepsakes people love to share.",
        facts: [
            { term: "Client", value: "Ray-Ban" },
            { term: "Format", value: "Photo activation" },
            { term: "Year", value: null },
            { term: "Output", value: "Branded photo strip" },
        ] as Phase2Fact[],
        imageAlt: "Ray-Ban Strip Photo activation",
        fallbackGalleryAlts: ["Strip photo activation", "Guests using strip photo", "Printed strip photo"],
        briefTitle: "The brief",
        briefCopy: "Ray-Ban wanted a photo experience that blends their iconic style with a shareable moment—one that moves beyond the booth and becomes part of the night.",
        experienceTitle: "The experience",
        experienceCopy: "Guests step in, strike a pose, and our system captures a sequence of frames that reflect their energy. The result is a premium photo strip, instantly printed and ready to share.",
        systemTitle: "The system",
        system: [
            { title: "Capture", copy: "AI cameras capture a burst of frames, freezing authentic expressions in motion." },
            { title: "Brand layer", copy: "Ray-Ban branding and frame designs are applied to every strip in real time." },
            { title: "Print", copy: "High-quality prints are delivered instantly—made to keep." },
            { title: "Share", copy: "Guests scan a QR to get their digital strip and share the moment." },
        ],
        impact: [
            { value: "1.8K+", label: "Live participation" },
            { value: "92%", label: "Instant output" },
            { value: "67%", label: "Shareable moment" },
        ],
        quote: "“It’s more than a photo. It’s a moment people want to keep and a story they want to share. That’s the power of experience.”",
        quoteCite: "Ray-Ban team",
        nextLabel: "Next project",
        nextTitle: "Pegasus ×\nDigital Gift Wheel",
        nextAlt: "Pegasus Digital Gift Wheel",
        nextHref: enPaths.projectHref(phase2ProjectSlugs.nextProject.en),
        ctaSolid: "Build an experience",
        ctaOutline: "people take with them.",
        ctaButton: "Plan Your Activation",
    },

    capabilityDetail: {
        crumb: "Capabilities  /  AI Photo + Video",
        heroSolid: "AI Photo +",
        heroOutline: "Video",
        heroLabel: "AI Photo and Video",
        heroCopyBefore: "Campaign-specific visual worlds, generated ",
        heroCopyEmphasis: "live.",
        facts: [
            { term: "Input", value: "Guest portrait" },
            { term: "Engine", value: "Custom AI" },
            { term: "Output", value: "Share + print" },
        ],
        imageAlt: "AI portrait capture connected to a live generated portrait wall",
        formatsTitle: "What we can build",
        formats: [
            { title: "AI Portrait", copy: "AI-enhanced portraits with branded backdrops, styles and layouts." },
            { title: "Face Swap", copy: "Real-time face swap experiences with themed templates." },
            { title: "Virtual Try-On", copy: "Try-on experiences for products, outfits and accessories." },
            { title: "AI Greenbox", copy: "Place guests in any scene with AI background generation." },
            { title: "AI Draw", copy: "Turn simple sketches or prompts into polished visual artwork." },
            { title: "Branded Video", copy: "Short AI-powered video clips with custom motion and effects." },
        ],
        formatLink: "Explore format",
        flowTitle: "From capture to campaign asset",
        flow: [
            { number: "01", title: "Capture", copy: "Guest captured on-site with optimized lighting." },
            { number: "02", title: "Generate", copy: "AI transforms the portrait into the selected format." },
            { number: "03", title: "Brand", copy: "Campaign elements and layouts are applied." },
            { number: "04", title: "Review", copy: "Operators approve the result in real time." },
            { number: "05", title: "Deliver", copy: "Share, print or save in high resolution." },
        ],
        liveSolid: "Built for",
        liveOutline: "live",
        liveTail: "conditions.",
        liveLabel: "Built for live conditions",
        guarantees: [
            { title: "Fast output", copy: "Optimized AI pipelines deliver high-quality results in seconds." },
            { title: "Brand guardrails", copy: "Predefined rules protect brand identity across every output." },
            { title: "On-site operation", copy: "Built for events with reliable hardware and on-site crew workflows." },
            { title: "Data & consent", copy: "Secure storage, guest consent flows and data handling compliance." },
        ],
        selectedTitle: "Selected AI Photo work",
        selected: [
            { slug: "defacto-x-afra-saracoglu-ai-fashion-experience", title: "DeFacto × Afra Saraçoğlu", alt: "DeFacto AI fashion experience", image: "https://res.cloudinary.com/dqkehdebg/image/upload/v1776151672/metasoftco/projects/s2tx0odiouo33iv3evpz.png" },
            { slug: "adidas-evo-sl-x-ai-try-on-photo", title: "Adidas EVO SL × AI Try-On", alt: "Adidas AI try-on", image: "https://res.cloudinary.com/dqkehdebg/image/upload/v1774878244/metasoftco/projects/zm4fhoverbifgnm2agsj.png" },
            { slug: "tavuk-dunyasi-x-ai-photo", title: "Tavuk Dünyası × AI Photo", alt: "Tavuk Dünyası AI Photo", image: "https://res.cloudinary.com/dqkehdebg/image/upload/v1784029645/metasoftco/projects/w3ixfgdzqbywnyv12ddg.png" },
        ],
        ctaSolid: "Turn one portrait",
        ctaOutline: "into a campaign moment.",
        ctaPrimary: "Plan Your Activation",
        ctaSecondary: "See Selected Work",
    },

    caseStudy: {
        breadcrumbAria: "Breadcrumb",
        crumbHome: "Home",
        crumbWork: "Work",
        title: "Tavuk Dünyası × AI Photo",
        eyebrow: "CASE STUDY · AI PHOTO",
        lede: "A live AI portrait experience that placed guests inside a visual world created for Tavuk Dünyası—and delivered a branded image they could take with them.",
        facts: [
            { term: "CLIENT", value: "Tavuk Dünyası" },
            { term: "FORMAT", value: "AI Photo activation" },
            { term: "YEAR", value: null },
            { term: "OUTPUT", value: "Branded digital portrait" },
        ] as Phase2Fact[],
        imageAlt: "Tavuk Dünyası AI Photo campaign portrait",
        imageCaption: "CAMPAIGN OUTPUT · TAVUK DÜNYASI",
        opportunityEyebrow: "THE OPPORTUNITY",
        opportunityTitle: "Turn the audience into the campaign image.",
        opportunityLede: "The experience gave each participant a personal role in a Tavuk Dünyası visual world. The creative idea, capture flow and final branded composition were treated as one connected guest journey.",
        opportunityCopy: "Instead of asking people to watch the content, the activation made their own portrait the content—creating a direct, memorable interaction with the campaign.",
        conceptEyebrow: "THE CONCEPT",
        conceptTitle: "A branded scene, completed by the guest.",
        conceptCopy: "The visual direction was designed to hold together as campaign content while leaving enough space for every participant to become the focal point.",
        journey: [
            { number: "01", title: "Guest portrait", copy: "A participant steps into the branded capture experience." },
            { number: "02", title: "Campaign scene", copy: "The portrait enters a visual scenario developed for Tavuk Dünyası." },
            { number: "03", title: "AI rendering", copy: "The live image pipeline creates the personalised final composition." },
            { number: "04", title: "Digital takeaway", copy: "The guest receives the branded result as a shareable image." },
        ],
        executionEyebrow: "PHYSICAL EXECUTION",
        executionTitle: "From screen interaction to personal takeaway.",
        executionCopy: "The project record shows the experience as a physical event installation: a branded kiosk, a simple guest-facing flow and an AI-generated image delivered at the end.",
        executionChecklist: [
            "Branded kiosk and interface",
            "Live portrait capture",
            "Real-time AI image pipeline",
            "Digital result for the guest",
        ],
        videoTitle: "Tavuk Dünyası AI Photo activation in use",
        galleryEyebrow: "CAMPAIGN OUTPUTS",
        galleryTitle: "One visual system, multiple personal portraits.",
        galleryAlt: (index: number) => `Tavuk Dünyası AI portrait ${index}`,
        recordEyebrow: "WHAT THE PROJECT DEMONSTRATES",
        recordTitle: "Creative direction, custom software and live delivery working as one.",
        record: [
            "A brand-specific visual concept rather than a generic effect.",
            "A guest journey designed for a physical live environment.",
            "A personalised digital asset that extends the interaction beyond the kiosk.",
            "A connected build across interface, AI processing and event installation.",
        ],
        capabilityLabel: "RELATED CAPABILITY",
        capabilityTitle: "AI Photo Booth for Events",
        capabilityHref: enPaths.capabilityDetailHref,
        finalEyebrow: "START A CONVERSATION",
        finalTitle: "Build a similar experience for your campaign.",
        finalCopy: "Bring us the audience, venue and visual idea. We’ll turn it into a practical guest journey and a live-ready system.",
        finalPrimary: "Build a Similar Experience",
        finalSecondary: "Explore More Work",
    },

    /** Presentation overrides for the three homepage hero projects, keyed by English slug. */
    featuredProjects: {
        "tavuk-dunyasi-x-ai-photo": { title: "Tavuk Dünyası × AI Photo", category: "AI Photo Activation" },
        "pegasus-airlines-digital-gift-wheel-activation": { title: "Pegasus × Digital Gift Wheel", category: "Interactive Game" },
        "ray-ban-x-strip-photo": { title: "Ray-Ban × Strip Photo", category: "Photo Activation" },
    } as Record<string, { title: string; category: string }>,
};

export type Phase2Copy = typeof en;

const tr: Phase2Copy = {
    locale: "tr",
    routes: trPaths.routes,

    nav: {
        skipLink: "İçeriğe geç",
        homeAria: "MetasoftCo ana sayfa",
        primaryAria: "Ana menü",
        mobileAria: "Mobil menü",
        openMenu: "Menüyü aç",
        closeMenu: "Menüyü kapat",
        localeSwitchAria: "İngilizceye geç",
        localeSwitchLabel: "TR / EN",
        cta: "Aktivasyonunuzu Planlayın",
        items: [
            { href: trPaths.routes.work, label: "Projeler" },
            { href: trPaths.routes.capabilities, label: "Hizmetler" },
            { href: trPaths.routes.about, label: "Hakkımızda" },
            { href: trPaths.routes.insights, label: "Blog" },
            { href: trPaths.routes.contact, label: "İletişim" },
        ],
    },

    footer: {
        tagline: "Markalar ve ajanslar için İstanbul'da geliştirilen yapay zeka destekli deneyim teknolojisi.",
        exploreLabel: "KEŞFET",
        contactLabel: "İLETİŞİM",
        followLabel: "TAKİP EDİN",
        city: "Üniversite Mah. Sarıgül Sk. İstanbul Teknokent No: 37/1 İç Kapı No: 28, Avcılar / İstanbul",
        baseline: "Konsept · Yazılım · Fiziksel üretim · Canlı operasyon",
        links: [
            { href: trPaths.routes.work, label: "Projeler" },
            { href: trPaths.routes.capabilities, label: "Hizmetler" },
            { href: trPaths.routes.about, label: "Hakkımızda" },
            { href: trPaths.routes.contact, label: "İletişim" },
        ],
    },

    home: {
        heroEyebrow: "YAPAY ZEKA DESTEKLİ DENEYİM TEKNOLOJİSİ",
        // Mirrors the English structure: the outline word is the subject and the
        // solid stack is the predicate, keeping every solid line short enough to
        // clear the portal image and the brief column.
        heroTitleOutline: "Deneyimler",
        heroTitleSolid: ["Markayı", "İnsana", "Bağlar"],
        heroTitleLabel: "Deneyimler markayı insana bağlar",
        heroFigureAlt: "Ray-Ban fotoğraf aktivasyonuna katılan misafirler",
        heroFigureLabel: "CANLI KATILIM",
        heroFigureCaption: "Ray-Ban · Strip Photo",
        heroBrief: "MetasoftCo; markalar ve ajanslar için markalı fotoğraf, video, oyun ve kurulum deneyimleri üretir. Kreatif yönetim, özel yazılım ve canlı prodüksiyonu tek elde birleştiririz.",
        heroPrimaryCta: "Aktivasyonunuzu Planlayın",
        heroSecondaryCta: "Seçili İşleri Görün",
        brandLoopAria: "Seçili marka iş birlikleri",
        brandLoopEyebrow: "GELECEĞE BAKAN MARKALARIN TERCİHİ",
        workEyebrow: "SEÇİLİ İŞLER",
        workTitle: "{İnsanların}\niçine\ngirdiği\nişler.",
        workCopy: "Gerçek insanlar, gerçek anlar. Katılıma davet eden ve kalıcı marka bağı kuran deneyimler tasarlıyoruz.",
        workLinkLabel: "Projeyi incele",
        workFallbackCategory: "Canlı Deneyim",
        capabilitiesEyebrow: "HİZMETLER",
        capabilitiesSrTitle: "Hizmetler",
        capabilities: [
            { number: "01", title: "Yapay zeka fotoğraf ve video", copy: "Misafir portresini markalı içeriğe dönüştüren, kampanyaya özel görsel dünyalar.", href: trPaths.categoryHref.ai },
            { number: "02", title: "Fotoğraf aktivasyonları", copy: "Mekâna, markaya ve paylaşım yolculuğuna göre kurgulanan fiziksel çekim deneyimleri.", href: trPaths.categoryHref.photo },
            { number: "03", title: "İnteraktif oyunlar", copy: "Dokunma, hareket ve rekabeti markalı ve oyunlaştırılmış katılıma çeviririz.", href: trPaths.categoryHref.interactive },
            { number: "04", title: "Özel kurulumlar", copy: "Yazılım, arayüz ve fiziksel sistemler tek bir canlı deneyim olarak geliştirilir.", href: trPaths.routes.capabilities },
        ],
        processEyebrow: "NASIL ÜRETİYORUZ",
        processSrTitle: "Nasıl üretiyoruz",
        process: [
            { number: "01", title: "Brief'i netleştiririz", copy: "Hedef kitle, mekân, kampanya fikri ve istenen misafir yolculuğu." },
            { number: "02", title: "Deneyimi prototipleriz", copy: "Kreatif yön, etkileşim akışı ve teknik kavram doğrulaması." },
            { number: "03", title: "Sistemi kurarız", copy: "Özel yazılım, markalı arayüz, içerik ve fiziksel entegrasyon." },
            { number: "04", title: "Sahada teslim ederiz", copy: "Kurulum, etkinlik günü operasyonu ve brief'e göre şekillenen teslim." },
        ],
        valueEyebrow: "NEDEN İNTERAKTİF",
        valueTitle: "Marka\nhikâyesinde\nkitleye\nbir {rol}\nverin.",
        valueTitleLabel: "Marka hikâyesinde kitleye bir rol verin.",
        valuePoints: [
            "İnsanlar izlediklerini değil, yaptıklarını hatırlar.",
            "Katılım duygusal bağ ve güven yaratır.",
            "Paylaşılabilir anlar erişimi mekânın çok ötesine taşır.",
            "Veri ve içgörüler her aktivasyonu bir adım ileri götürür.",
        ],
        finalEyebrow: "SIRADAKİ SİNYAL",
        finalTitle: "Sıradaki kampanyanız\n{insanların içine girebileceği bir şey olsun.}",
        finalTitleLabel: "Sıradaki kampanyanız insanların içine girebileceği bir şey olsun.",
        finalCopy: "Hedef kitleyi, mekânı ve kampanya hedefini paylaşın. Etkileşimi, sistemi ve canlı teslimi brief'inize göre kurgulayalım.",
        finalCta: "Aktivasyonunuzu Planlayın",
    },

    about: {
        heroSolid: "Teknolojiyi",
        heroOutline: "sahneye çıkarıyoruz.",
        heroLabel: "Teknolojiyi sahneye çıkarıyoruz.",
        locationChip: "İstanbul  /  2020'den beri",
        heroCopy: "Kreatif yönetim, özel yazılım, fiziksel üretim ve canlı operasyonu bir araya getirerek markalarla insanları gerçek zamanlı buluşturan deneyimler tasarlıyor ve sahaya çıkarıyoruz.",
        storyTitle: "İstanbul'da kurulur.\nSahnede çalışır.",
        storyParagraphs: [
            "Kreatif yönetimi, yazılımı, fiziksel üretimi ve canlı operasyonu tek çatı altında topluyoruz.",
            "Konseptten canlı teslime kadar; güvenilir, ölçülebilir ve insanları harekete geçiren deneyimler kuruyoruz.",
        ],
        stats: [
            { value: "1.000+", label: "Canlı etkinlik" },
            { value: "100+", label: "Marka" },
            { value: "5+", label: "Yıl" },
            { value: "Tek", label: "Uçtan uca ekip" },
        ],
        principles: [
            { title: "Katılımcı olsun", copy: "Dikkat için değil, aksiyon için tasarlarız." },
            { title: "Canlı koşullara dayansın", copy: "Beklenmedik olana hazırlanır, yine de teslim ederiz." },
            { title: "Geriye bir şey kalsın", copy: "Paylaşmaya değer anlar yaratırız." },
        ],
        finalSolid: "Brief'i siz getirin.",
        finalOutline: "Deneyimi biz kuralım.",
        finalCta: "Aktivasyonunuzu Planlayın",
    },

    contact: {
        heroSolid: "İnsanların\niçine girebileceği",
        heroOutline: "bir şey kuralım.",
        heroLabel: "İnsanların içine girebileceği bir şey kuralım.",
        heroCopy: "Hedef kitleyi, mekânı ve kampanya hedefini paylaşın. Deneyimi birlikte şekillendirelim.",
        asideTitle: "Bir konuşmayla başlayalım",
        location: "İstanbul, Türkiye",
        replyTime: "Bir iş günü içinde dönüş",
        figureAlt: "Etkinlik brief'ini inceleyen MetasoftCo prodüksiyon ekibi",
        form: {
            name: "Ad Soyad *",
            namePlaceholder: "Adınız ve soyadınız",
            company: "Şirket *",
            companyPlaceholder: "Şirket adı",
            email: "E-posta *",
            emailPlaceholder: "ornek@sirket.com",
            phone: "Telefon *",
            phonePlaceholder: "+90 5XX XXX XX XX",
            event: "Etkinlik / kampanya *",
            eventPlaceholder: "Etkinlik veya kampanya adı",
            venue: "Mekân + şehir *",
            venuePlaceholder: "Mekân adı ve şehir",
            date: "Hedef tarih *",
            audience: "Beklenen katılımcı *",
            audiencePlaceholder: "Tahmini kişi sayısı",
            budget: "Bütçe aralığı *",
            budgetPlaceholder: "Bütçe aralığı seçin",
            budgetOptions: ["€5B–€10B", "€10B–€25B", "€25B+"],
            experienceLegend: "Nasıl bir deneyim planlıyorsunuz? *",
            experienceTypes: ["Yapay Zeka Fotoğraf + Video", "Fotoğraf Aktivasyonları", "İnteraktif Oyunlar", "Özel Kurulumlar"],
            brief: "Brief'inizi anlatın *",
            briefPlaceholder: "Hedefleriniz, kitleniz, mesajınız, olmazsa olmazlarınız ve referanslarınız…",
            submit: "Brief'i gönder",
            submitting: "Gönderiliyor…",
            submitted: "Brief alındı",
            success: "Teşekkürler — brief'iniz ekibimize ulaştı. Bir iş günü içinde size dönüş yapacağız.",
            error: "Brief gönderilemedi. Lütfen info@metasoftco.com adresine yazın veya tekrar deneyin.",
        },
        nextStepsTitle: "Bundan sonra ne olacak",
        nextSteps: [
            { number: "01", title: "İnceleriz", copy: "Brief'inizi inceler, doğru soruları sorarız." },
            { number: "02", title: "Yaklaşımı kurarız", copy: "Doğru deneyimi ve teknik planı tasarlarız." },
            { number: "03", title: "Teslimi planlarız", copy: "Ekibi ve takvimi hizalar, işi eksiksiz teslim ederiz." },
        ],
        liteTitle: "Henüz tam bir brief'iniz yok mu?",
        liteCopy: "Sorun değil. Bize yazın ya da işlerimizi inceleyin.",
        liteMailLabel: "E-posta gönderin",
        liteWorkLabel: "Seçili işleri inceleyin",
        finalSolid: "Sıradaki",
        finalOutline: "canlı an",
        finalTail: "burada başlıyor.",
    },

    work: {
        heroSolid: "İnsanların\niçine girdiği",
        heroOutline: "işler.",
        heroLabel: "İnsanların içine girdiği işler.",
        heroCopy: "Kitleyi katılımcıya, anı marka bağına dönüştüren deneyim aktivasyonları tasarlıyor ve sahaya çıkarıyoruz.",
        catalogAria: "Tüm projeler",
        cardLink: "Projeyi İncele",
        ctaSolid: "Sıradaki kampanya",
        ctaOutline: "insanların içine girebileceği bir şey olsun.",
        ctaLabel: "Sıradaki kampanya insanların içine girebileceği bir şey olsun.",
        ctaButton: "Aktivasyonunuzu Planlayın",
    },

    capabilities: {
        heroSolid: "Anın ardındaki",
        heroOutline: "sistemi kuruyoruz.",
        heroLabel: "Anın ardındaki sistemi kuruyoruz.",
        heroCopy: "Kreatif yönetim, özel yazılım, fiziksel üretim ve canlı operasyonu birleştirerek markalarla insanları gerçek zamanlı buluşturan deneyimler tasarlıyor ve teslim ediyoruz.",
        catalogAria: "Hizmetler",
        cardLink: "Hizmeti İncele",
        endToEndTitle: "Tek ekip,\nuçtan uca",
        process: [
            { number: "01", title: "Brief", copy: "Dinler, öğrenir; hedef, kitle ve başarı kriterinde hizalanırız." },
            { number: "02", title: "Tasarım", copy: "Konsepti, deneyim akışını ve teknik planı kurgularız." },
            { number: "03", title: "Üretim", copy: "Her bileşeni titizlikle geliştirir, test eder ve entegre ederiz." },
            { number: "04", title: "Teslim", copy: "Sahaya çıkar, operasyonu yürütür ve etkiyi optimize ederiz." },
        ],
        ctaSolid: "Brief'i",
        ctaOutline: "canlı bir deneyime çevirin.",
        ctaButton: "Aktivasyonunuzu Planlayın",
    },

    workDetail: {
        crumb: "Projeler  /  Vaka Analizi  /  01",
        heroSolid: "Ray-Ban ×",
        heroOutline: "Strip Photo",
        heroCopy: "Anları, insanların paylaşmayı sevdiği ikonik hatıralara dönüştüren yapay zeka destekli bir fotoğraf aktivasyonu.",
        facts: [
            { term: "Marka", value: "Ray-Ban" },
            { term: "Format", value: "Fotoğraf aktivasyonu" },
            { term: "Yıl", value: null },
            { term: "Çıktı", value: "Markalı fotoğraf şeridi" },
        ],
        imageAlt: "Ray-Ban Strip Photo aktivasyonu",
        fallbackGalleryAlts: ["Strip photo aktivasyonu", "Strip photo kullanan misafirler", "Basılmış fotoğraf şeridi"],
        briefTitle: "Brief",
        briefCopy: "Ray-Ban, ikonik stilini paylaşılabilir bir anla birleştiren; kabinin ötesine geçip gecenin parçası olan bir fotoğraf deneyimi istedi.",
        experienceTitle: "Deneyim",
        experienceCopy: "Misafir içeri girer, poz verir; sistemimiz enerjisini yansıtan bir kare dizisi yakalar. Sonuç, anında basılan ve paylaşılmaya hazır premium bir fotoğraf şerididir.",
        systemTitle: "Sistem",
        system: [
            { title: "Çekim", copy: "Yapay zeka kameraları arka arkaya kareler alarak gerçek ifadeleri hareket hâlinde dondurur." },
            { title: "Marka katmanı", copy: "Ray-Ban marka öğeleri ve çerçeve tasarımları her şeride gerçek zamanlı işlenir." },
            { title: "Baskı", copy: "Yüksek kaliteli baskılar anında teslim edilir — saklanmak için." },
            { title: "Paylaşım", copy: "Misafirler QR okutarak dijital şeridini alır ve anı paylaşır." },
        ],
        impact: [
            { value: "1.8K+", label: "Canlı katılım" },
            { value: "%92", label: "Anında çıktı" },
            { value: "%67", label: "Paylaşılan an" },
        ],
        quote: "“Bu bir fotoğraftan fazlası. İnsanların saklamak istediği bir an ve anlatmak istediği bir hikâye. Deneyimin gücü tam olarak bu.”",
        quoteCite: "Ray-Ban ekibi",
        nextLabel: "Sıradaki proje",
        nextTitle: "Pegasus ×\nDijital Hediye Çarkı",
        nextAlt: "Pegasus Dijital Hediye Çarkı",
        nextHref: trPaths.projectHref(phase2ProjectSlugs.nextProject.tr),
        ctaSolid: "İnsanların yanında götürdüğü",
        ctaOutline: "bir deneyim kurun.",
        ctaButton: "Aktivasyonunuzu Planlayın",
    },

    capabilityDetail: {
        crumb: "Hizmetler  /  Yapay Zeka Fotoğraf + Video",
        heroSolid: "Yapay Zeka",
        heroOutline: "Fotoğraf + Video",
        heroLabel: "Yapay Zeka Fotoğraf ve Video",
        heroCopyBefore: "Kampanyaya özel görsel dünyalar, ",
        heroCopyEmphasis: "canlı üretilir.",
        facts: [
            { term: "Girdi", value: "Misafir portresi" },
            { term: "Motor", value: "Özel yapay zeka" },
            { term: "Çıktı", value: "Paylaşım + baskı" },
        ],
        imageAlt: "Canlı üretilen portre duvarına bağlı yapay zeka portre çekim istasyonu",
        formatsTitle: "Neler kurabiliriz",
        formats: [
            { title: "AI Portrait", copy: "Markalı fonlar, stiller ve yerleşimlerle yapay zeka destekli portreler." },
            { title: "Face Swap", copy: "Temalı şablonlarla gerçek zamanlı yüz değiştirme deneyimleri." },
            { title: "Sanal Deneme", copy: "Ürün, kıyafet ve aksesuarlar için sanal deneme deneyimleri." },
            { title: "AI Greenbox", copy: "Yapay zeka arka plan üretimiyle misafirleri istediğiniz sahneye taşıyın." },
            { title: "AI Draw", copy: "Basit çizimleri veya metinleri işlenmiş görsel eserlere dönüştürün." },
            { title: "Markalı Video", copy: "Özel hareket ve efektlerle yapay zeka destekli kısa video klipler." },
        ],
        formatLink: "Formatı inceleyin",
        flowTitle: "Çekimden kampanya varlığına",
        flow: [
            { number: "01", title: "Çekim", copy: "Misafir, optimize edilmiş ışıkla sahada çekilir." },
            { number: "02", title: "Üretim", copy: "Yapay zeka portreyi seçilen formata dönüştürür." },
            { number: "03", title: "Markalama", copy: "Kampanya öğeleri ve yerleşimler uygulanır." },
            { number: "04", title: "Kontrol", copy: "Operatörler sonucu gerçek zamanlı onaylar." },
            { number: "05", title: "Teslim", copy: "Yüksek çözünürlükte paylaşın, bastırın veya kaydedin." },
        ],
        liveSolid: "Canlı koşullar",
        liveOutline: "için",
        liveTail: "kurulur.",
        liveLabel: "Canlı koşullar için kurulur",
        guarantees: [
            { title: "Hızlı çıktı", copy: "Optimize edilmiş yapay zeka hatları saniyeler içinde yüksek kaliteli sonuç üretir." },
            { title: "Marka koruması", copy: "Önceden tanımlı kurallar her çıktıda marka kimliğini korur." },
            { title: "Sahada operasyon", copy: "Güvenilir donanım ve saha ekibi akışlarıyla etkinlikler için kurgulanır." },
            { title: "Veri & açık rıza", copy: "Güvenli saklama, misafir onay akışları ve KVKK uyumlu veri yönetimi." },
        ],
        selectedTitle: "Seçili yapay zeka fotoğraf işleri",
        selected: [
            { slug: "defacto-x-afra-saracoglu-ai-fashion-experience", title: "DeFacto × Afra Saraçoğlu", alt: "DeFacto yapay zeka moda deneyimi", image: "https://res.cloudinary.com/dqkehdebg/image/upload/v1776151672/metasoftco/projects/s2tx0odiouo33iv3evpz.png" },
            { slug: "adidas-evo-sl-x-ai-try-on-photo", title: "Adidas EVO SL × AI Try-On", alt: "Adidas yapay zeka sanal deneme", image: "https://res.cloudinary.com/dqkehdebg/image/upload/v1774878244/metasoftco/projects/zm4fhoverbifgnm2agsj.png" },
            { slug: "tavuk-dunyasi-x-ai-photo", title: "Tavuk Dünyası × AI Photo", alt: "Tavuk Dünyası AI Photo", image: "https://res.cloudinary.com/dqkehdebg/image/upload/v1784029645/metasoftco/projects/w3ixfgdzqbywnyv12ddg.png" },
        ],
        ctaSolid: "Tek bir portreyi",
        ctaOutline: "kampanya anına çevirin.",
        ctaPrimary: "Aktivasyonunuzu Planlayın",
        ctaSecondary: "Seçili İşleri Görün",
    },

    caseStudy: {
        breadcrumbAria: "Sayfa yolu",
        crumbHome: "Ana sayfa",
        crumbWork: "Projeler",
        title: "Tavuk Dünyası × AI Photo",
        eyebrow: "VAKA ANALİZİ · AI PHOTO",
        lede: "Misafirleri Tavuk Dünyası için üretilmiş bir görsel dünyanın içine yerleştiren ve yanlarında götürebilecekleri markalı bir görsel sunan canlı yapay zeka portre deneyimi.",
        facts: [
            { term: "MARKA", value: "Tavuk Dünyası" },
            { term: "FORMAT", value: "AI Photo aktivasyonu" },
            { term: "YIL", value: null },
            { term: "ÇIKTI", value: "Markalı dijital portre" },
        ],
        imageAlt: "Tavuk Dünyası AI Photo kampanya portresi",
        imageCaption: "KAMPANYA ÇIKTISI · TAVUK DÜNYASI",
        opportunityEyebrow: "FIRSAT",
        opportunityTitle: "Kitleyi kampanya görselinin kendisi yapın.",
        opportunityLede: "Deneyim, her katılımcıya Tavuk Dünyası görsel dünyasında kişisel bir rol verdi. Kreatif fikir, çekim akışı ve markalı son kompozisyon tek bir bütünleşik misafir yolculuğu olarak ele alındı.",
        opportunityCopy: "Aktivasyon, insanlardan içeriği izlemelerini istemek yerine kendi portrelerini içeriğin kendisi hâline getirdi; kampanyayla doğrudan ve akılda kalıcı bir etkileşim kurdu.",
        conceptEyebrow: "KONSEPT",
        conceptTitle: "Misafirin tamamladığı markalı bir sahne.",
        conceptCopy: "Görsel yön, kampanya içeriği olarak bütünlüğünü korurken her katılımcının odak noktası olmasına yetecek alanı bırakacak şekilde tasarlandı.",
        journey: [
            { number: "01", title: "Misafir portresi", copy: "Katılımcı markalı çekim deneyiminin içine adım atar." },
            { number: "02", title: "Kampanya sahnesi", copy: "Portre, Tavuk Dünyası için geliştirilen görsel senaryoya girer." },
            { number: "03", title: "Yapay zeka üretimi", copy: "Canlı görüntü hattı kişiselleştirilmiş son kompozisyonu oluşturur." },
            { number: "04", title: "Dijital hatıra", copy: "Misafir markalı sonucu paylaşılabilir bir görsel olarak alır." },
        ],
        executionEyebrow: "FİZİKSEL UYGULAMA",
        executionTitle: "Ekran etkileşiminden kişisel hatıraya.",
        executionCopy: "Proje kaydı deneyimi fiziksel bir etkinlik kurulumu olarak gösteriyor: markalı bir kiosk, sade bir misafir akışı ve sonunda teslim edilen yapay zeka üretimi bir görsel.",
        executionChecklist: [
            "Markalı kiosk ve arayüz",
            "Canlı portre çekimi",
            "Gerçek zamanlı yapay zeka görüntü hattı",
            "Misafire özel dijital sonuç",
        ],
        videoTitle: "Kullanımdaki Tavuk Dünyası AI Photo aktivasyonu",
        galleryEyebrow: "KAMPANYA ÇIKTILARI",
        galleryTitle: "Tek görsel sistem, sayısız kişisel portre.",
        galleryAlt: (index: number) => `Tavuk Dünyası yapay zeka portresi ${index}`,
        recordEyebrow: "PROJE NEYİ GÖSTERİYOR",
        recordTitle: "Kreatif yönetim, özel yazılım ve canlı teslim tek bir bütün olarak.",
        record: [
            "Genel bir efekt değil, markaya özel bir görsel konsept.",
            "Fiziksel ve canlı bir ortam için tasarlanmış misafir yolculuğu.",
            "Etkileşimi kioskun ötesine taşıyan kişiselleştirilmiş dijital varlık.",
            "Arayüz, yapay zeka işleme ve etkinlik kurulumunu birleştiren bütünleşik yapım.",
        ],
        capabilityLabel: "İLGİLİ HİZMET",
        capabilityTitle: "Etkinlikler için AI Photobooth",
        capabilityHref: trPaths.capabilityDetailHref,
        finalEyebrow: "BİR KONUŞMA BAŞLATIN",
        finalTitle: "Kampanyanız için benzer bir deneyim kuralım.",
        finalCopy: "Kitleyi, mekânı ve görsel fikri bize getirin. Bunu uygulanabilir bir misafir yolculuğuna ve sahaya hazır bir sisteme dönüştürelim.",
        finalPrimary: "Benzer Bir Deneyim Kurun",
        finalSecondary: "Diğer İşleri İnceleyin",
    },

    featuredProjects: {
        "tavuk-dunyasi-x-ai-photo": { title: "Tavuk Dünyası × AI Photo", category: "AI Photo Aktivasyonu" },
        "pegasus-airlines-digital-gift-wheel-activation": { title: "Pegasus × Dijital Hediye Çarkı", category: "İnteraktif Oyun" },
        "ray-ban-x-strip-photo": { title: "Ray-Ban × Strip Photo", category: "Fotoğraf Aktivasyonu" },
    },
};

const dictionaries = { tr, en } satisfies Record<Phase2Locale, Phase2Copy>;

export function phase2Copy(locale: Phase2Locale): Phase2Copy {
    return dictionaries[locale];
}
